<?php

?>

<h4>Regles du jeu :</h4>
<div style="text-align: left; font-size: small;">
    <p>L’ordinateur choisi une combinaison a 4 chiffres entre 1 et 6. </p>
    <p>Le joueur propose une combinaison L’ordinateur lui retourne un code sous forme de pion sans préciser quel chiffre corresepond a quel pion : un pion rouge par chiffre juste mais mal placé, et un pion blanc par chiffre bien placé </p>
    <p>Lorsque le code est 4 pions blanc le joueur a gagné et peut relancer une partie. </p>
</div>
        
<center><a class='btn btn-success btn-big' href='/play'>Jouer !</a></center>
