<!doctype html>
<html>
    <head>
        <!-- CONSIGNES : 
        Faites un jeu de MasterMind en ligne a un joueur contre l’ordinateur (le combinaison est crée aléatoirement)
        -->
    <title>Test Recrutement PHP MM</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        span.pion {
            font-size: 2.5em;
            line-height: 20px;
            margin: 0 -2px;
            text-shadow: 0 0 2px black;
        }
        .pion.blanc {
            color: white;
        }
        .pion.rouge {
            color: red;
        }

        main {
            margin: 80px auto;
            width: 80%;
            max-width: 600px;
            text-align: center;
        }

        table {
            width: 100%;
            max-width: 300px;
            margin: 20px auto;
            border-collapse: collapse;
        }
    </style>
</head>
<body>
        
    <main>

        <h1>MasterMind</h1>
        <h4>Regles du jeu :</h4>
        <div style="text-align: left; font-size: small;">
            <p>L’ordinateur choisi une combinaison a 4 chiffres entre 1 et 6. </p>
            <p>Le joueur propose une combinaison L’ordinateur lui retourne un code sous forme de pion sans préciser quel chiffre corresepond a quel pion : un pion rouge par chiffre juste mais mal placé, et un pion blanc par chiffre bien placé </p>
            <p>Lorsque le code est 4 pions blanc le joueur a gagné et peut relancer une partie. </p>
        </div>
    
        <form method="post" action="">
            <table class='table'>
                <tr>
                    <th colspan="4">Proposition</th>
                    <th>Résultat</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                    <td>
                        <span class="pion blanc">&bull;</span>
                        <span class="pion rouge">&bull;</span>
                    </td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                    <td>
                        <span class="pion blanc">&bull;</span>
                        <span class="pion rouge">&bull;</span>
                    </td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                    <td>
                        <span class="pion blanc">&bull;</span>
                        <span class="pion rouge">&bull;</span>
                    </td>
                </tr>
                <tr>
                    <th colspan="5">A vous de jouer !</th>
                </tr>
                <tr>
                    <td>
                        <select>
                            <option value=1>1</option>
                            <option value=2>2</option>
                            <option value=3>3</option>
                            <option value=4>4</option>
                            <option value=5>5</option>
                            <option value=6>6</option>
                        </select>
                    </td>
                    <td>
                        <select>
                            <option value=1>1</option>
                            <option value=2 selected>2</option>
                            <option value=3>3</option>
                            <option value=4>4</option>
                            <option value=5>5</option>
                            <option value=6>6</option>
                        </select>
                    </td>
                    <td>
                        <select>
                            <option value=1>1</option>
                            <option value=2>2</option>
                            <option value=3 selected>3</option>
                            <option value=4>4</option>
                            <option value=5>5</option>
                            <option value=6>6</option>
                        </select>
                    </td>
                    <td>
                        <select>
                            <option value=1>1</option>
                            <option value=2>2</option>
                            <option value=3>3</option>
                            <option value=4 selected>4</option>
                            <option value=5>5</option>
                            <option value=6>6</option>
                        </select>
                    </td>
                    <td><input type="submit" value="Valider"></td>
                </tr>
            </table> 
            <div class="alert alert-success" role="alert">
                <b>Bien joué !</b> Vous avez gagné en X coups ! <a href="">Rejouer</a>
            </div>       
        </form>
    </main>
</html>