<?php

//get masterming game from data
/** @var GameMastermind $m */
$m = $this->getData("mastermind");
$p = false;
$pindex = -1;

?>
<form method="post" action="play">
    <table class='table'>
        <tr>
            <td><small>#</small></td>
            <th colspan="<?= $m->getCombinationWidth() ?>">Proposition</th>
            <th>Résultat</th>
        </tr>
        <?php foreach($m->getPropositions() as $pindex => $p) : /** @var GameMastermindProposition $p */ ?>
        <tr>
            <td><small>#<?= $pindex + 1 ?></small></td>
            <?php for($i = 0; $i < $m->getCombinationWidth(); $i++) : ?>
                <td><?= $p->getCombination($i) ?></td>
            <?php endfor; ?>
            <td>
                <span class='nobr'>
                <?php for($i = 0; $i < $p->getValidCount(); $i++) : ?>
                    <span class="pion blanc">&bull;</span>
                <?php endfor; ?>
                <?php for($i = 0; $i < $p->getApproxCount(); $i++) : ?>
                    <span class="pion rouge">&bull;</span>
                <?php endfor; ?>
                </span>
            </td>
        </tr>
        <?php endforeach; ?>
        <?php if (!$m->isGameOver()) : ?>
        <tr>
            <th colspan="<?= $m->getCombinationWidth() + 2 ?>">A vous de jouer !</th>
        </tr>
        <tr>
            <td><small>#<?= $pindex + 2 ?>/<?= $m->getMaxAtemps() ?></small></td>
            <?php for($i = 0; $i < $m->getCombinationWidth(); $i++) : ?>
            <?php $selected = $p ? $p->getCombination($i) : random_int(1, $m->getCombinationHeight()) ?>
            <td>
                <select name='combination[]' >
                    <?php for($number = 1; $number <= $m->getCombinationHeight(); $number++) : ?>
                        <option value=<?= $number ?> <?= $number == $selected ? "selected=selected" : "" ?> ><?= $number ?></option>
                    <?php endfor; ?>
                </select>
            </td>
            <?php endfor; ?>
            <td><input type="submit" value="Valider"></td>
        </tr>
        <?php endif ?>
    </table> 
    
    <?php if ($m->getWinner()) : ?>
        <div class="alert alert-success" role="alert">
            <b>Bien joué !</b> Vous avez gagné en <?= count($m->getPropositions()) ?> coups !
        </div>    
        <a class='btn btn-success' href="/reset">Rejouer</a>
    <?php elseif ($m->isGameOver()) : ?>
        <div class="alert alert-danger" role="alert">
            <b>Raté !</b> Vous n'avez pas réussi a trouver le code <?= $m->getCombination() ?> en moins de <?= $m->getMaxAtemps() ?> coups ... 
        </div>    
        <a class='btn btn-warning' href="/reset">Rejouer</a>
    <?php endif ?>
</form>