<!doctype html>
<html>
    <head>
    <title>WeeMind</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        span.pion {
            font-size: 2.5em;
            line-height: 20px;
            margin: 0 -2px;
            text-shadow: 0 0 2px black;
        }
        .pion.blanc {
            color: white;
        }
        .pion.rouge {
            color: red;
        }

        main {
            margin: 80px auto;
            width: 80%;
            max-width: 600px;
            text-align: center;
        }

        table {
            width: 100%;
            max-width: 300px;
            margin: 20px auto;
            border-collapse: collapse;
        }
    </style>
</head>
<body>
        
    <main>

        <h1>MasterMind</h1>
        <h4>Regles du jeu :</h4>
        <div style="text-align: left; font-size: small;">
            <p>L’ordinateur choisi une combinaison a 4 chiffres entre 1 et 6. </p>
            <p>Le joueur propose une combinaison L’ordinateur lui retourne un code sous forme de pion sans préciser quel chiffre corresepond a quel pion : un pion rouge par chiffre juste mais mal placé, et un pion blanc par chiffre bien placé </p>
            <p>Lorsque le code est 4 pions blanc le joueur a gagné et peut relancer une partie. </p>
        </div>
    
        <?= $this->renderChildren() ?>
    </main>
</html>