<!doctype html>
<html>
    <head>
    <title>WeeMind</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <style>
        span.pion {
            font-size: 2.5em;
            line-height: 20px;
            margin: 0 -2px;
            text-shadow: 0 0 2px black;
        }
        .pion.blanc {
            color: white;
        }
        .pion.rouge {
            color: red;
        }

        main {
            margin: 80px auto;
            width: 80%;
            max-width: 600px;
            text-align: center;
        }

        table {
            width: 100%;
            max-width: 300px;
            margin: 20px auto;
            border-collapse: collapse;
        }
        
        th {
            text-align: center;
        }
        
        .form-control {
            width: 80px;
            text-align: center;
            margin: 0 auto;
        }
        
        small {
            color:#999;
            font-size: 75%;
        }
        
        .nobr {
            white-space: nowrap;
            word-wrap: unset;
        }
    </style>
</head>
<body>
        
    <main>
        <h1>WeeMind</h1>
        <div>
        <a class='btn btn-warning' href='/index'><i class="bi bi-house"></i></a> 
        <a class='btn btn-success' href='/play'><i class="bi bi-joystick"></i></a> 
        <a class='btn btn-primary' href='/settings'><i class="bi bi-sliders2"></i></a> 
        </div>
        <br>
        
        <?= $this->renderChildren() ?>
    </main>
</html>